version: '3.8'

services:
  db:
    image: mysql/mysql-server:8.0
    container_name: db01
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: MySQL
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql
      - ./src/main/resources/accountsdb.sql:/docker-entrypoint-initdb.d/accountsdb.sql
    networks:
      - vpronet

  memcache:
    image: memcached:1.6-alpine 
    container_name: mc01
    ports:
      - "11211:11211"
    networks:
      - vpronet

  rabbitmq:
    image: rabbitmq:3.12-management-alpine 
    container_name: rmq01
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - vpronet

  vproapp:
    image: 650576187890.dkr.ecr.ap-south-1.amazonaws.com/three-tier-application
    container_name: vproapp01
    ports:
      - "9000:8080"
    networks:
      - vpronet
    depends_on:
      - db
      - memcache
      - rabbitmq

  jenkins:
    image: jenkins/jenkins:lts-alpine
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - vpronet

volumes:
  dbdata:

networks:
  vpronet:


